spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL

security:
  jwt:
    secret: changeit
    expiration-time: 864000000
    token-prefix: Bearer
    header: Authorization